import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Clock3, FileText, Loader2, PackageCheck, Plus, RefreshCw, Save, WalletCards } from "lucide-react";
import { PageHeader } from "@/admin/components/PageHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { FitInput as Input, FitTextarea as Textarea } from "@/components/fit/FitFormControls";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { supabase } from "@/integrations/supabase/client";
import { fmtMAD } from "@/lib/format";
import { toast } from "sonner";
import { useSearchParams } from "react-router-dom";

const db = supabase as any;
const statusLabels: Record<string,string> = { not_requested:"Non demandé",request_ready:"Demande prête",sent:"Envoyé",waiting_supplier:"Attente fournisseur",supplier_replied:"Réponse reçue",option_hold:"Option / Hold",confirmed:"Confirmé",unavailable:"Indisponible",alternative_proposed:"Alternative proposée",cancelled:"Annulé",paid:"Payé",voucher_received:"Voucher reçu" };
const statusOptions = Object.keys(statusLabels);
const terminalStatuses = ["supplier_replied","confirmed","unavailable","alternative_proposed","cancelled","paid","voucher_received"];

export default function FitSupplierControl() {
  const [searchParams]=useSearchParams();
  const [rows,setRows]=useState<any[]>([]); const [quotes,setQuotes]=useState<any[]>([]); const [suppliers,setSuppliers]=useState<any[]>([]); const [staff,setStaff]=useState<any[]>([]); const [alternatives,setAlternatives]=useState<any[]>([]); const [attachments,setAttachments]=useState<any[]>([]); const [drafts,setDrafts]=useState<Record<string,any>>({});
  const [selectedQuote,setSelectedQuote]=useState(searchParams.get("quote")||""); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState("");
  const load=async()=>{ setLoading(true); const [{data:r,error},{data:q},{data:s},{data:people},{data:a},{data:files}]=await Promise.all([
    db.from("fit_supplier_requests").select("*,supplier:supplier_id(id,name),quote:quote_id(id,quote_number,quote_family_reference,version_number,client_name,commercial_status,total_selling_price_mad,accepted_amount_mad)").order("updated_at",{ascending:false}),
    db.from("fit_quotes").select("id,quote_number,quote_family_reference,version_number,client_name,commercial_status,accepted_snapshot_id").not("accepted_snapshot_id","is",null).is("deleted_at",null).order("updated_at",{ascending:false}),
    db.from("suppliers").select("id,name").order("name"),db.from("profiles").select("id,full_name").order("full_name"), db.from("fit_supplier_alternatives").select("*").order("created_at",{ascending:false}),db.from("fit_supplier_request_attachments").select("*").order("created_at",{ascending:false})]);
    setLoading(false); if(error){toast.error(error.message);return;} setRows(r||[]);setQuotes(q||[]);setSuppliers(s||[]);setStaff(people||[]);setAlternatives(a||[]);setAttachments(files||[]);setDrafts(Object.fromEntries((r||[]).map((x:any)=>[x.id,{...x}]))); };
  useEffect(()=>{void load();},[]);
  const stats=useMemo(()=>({ waiting:rows.filter(r=>["sent","waiting_supplier"].includes(r.status)).length,holds:rows.filter(r=>r.status==="option_hold").length,unavailable:rows.filter(r=>r.status==="unavailable").length,alternatives:alternatives.filter(a=>a.decision==="pending").length,confirmed:rows.filter(r=>["confirmed","paid","voucher_received"].includes(r.status)).length,payments:rows.filter(r=>r.payment_deadline&&!["paid","cancelled"].includes(r.status)).length }),[rows,alternatives]);
  const generate=async()=>{if(!selectedQuote)return;setBusy("generate");const{data,error}=await db.rpc("generate_fit_supplier_requests_v5",{p_quote_id:selectedQuote,p_follow_up_hours:24});setBusy("");if(error)return toast.error(error.message);toast.success(`${data?.created||0} demande(s) fournisseur créée(s).`);void load();};
  const updateDraft=(id:string,key:string,value:any)=>setDrafts(c=>({...c,[id]:{...c[id],[key]:value}}));
  const save=async(row:any)=>{const d=drafts[row.id];setBusy(row.id);const{error}=await db.from("fit_supplier_requests").update({supplier_id:d.supplier_id||null,assigned_staff_id:d.assigned_staff_id||null,status:d.status,follow_up_hours:Number(d.follow_up_hours||24),follow_up_at:d.follow_up_at||null,supplier_response:d.supplier_response||null,confirmation_number:d.confirmation_number||null,hold_release_deadline:d.hold_release_deadline||null,cancellation_deadline:d.cancellation_deadline||null,payment_deadline:d.payment_deadline||null,supplier_notes:d.supplier_notes||null,supplier_quoted_cost:d.supplier_quoted_cost===""?null:Number(d.supplier_quoted_cost),confirmed_cost:d.confirmed_cost===""?null:Number(d.confirmed_cost),final_cost:d.final_cost===""?null:Number(d.final_cost),currency:d.currency,exchange_rate_to_mad:Number(d.exchange_rate_to_mad||1)}).eq("id",row.id);setBusy("");if(error)return toast.error(error.message);toast.success("Demande fournisseur mise à jour.");void load();};
  const decide=async(alt:any,decision:string)=>{setBusy(alt.id);const{data,error}=await db.rpc("decide_fit_supplier_alternative_v5",{p_alternative_id:alt.id,p_decision:decision});if(!error&&decision==="client_revision"){const version=await db.rpc("create_new_fit_quote_version",{p_source_quote_id:data.quote_id});if(version.error){setBusy("");return toast.error(version.error.message);}}setBusy("");if(error)return toast.error(error.message);toast.success(decision==="client_revision"?"Nouvelle version client créée.":"Décision enregistrée.");void load();};
  const openFile=async(file:any)=>{const{data,error}=await supabase.storage.from("trip-documents").createSignedUrl(file.storage_path,120);if(error)return toast.error(error.message);window.open(data.signedUrl,"_blank","noopener,noreferrer")};
  return <div className="min-w-0 space-y-5 overflow-x-hidden"><PageHeader title="FIT Supplier Control" description="Promesses client, confirmations fournisseur et échéances opérationnelles — sans double saisie." />
    <Card className="grid gap-3 p-4 md:grid-cols-[minmax(0,1fr)_auto]"><Select value={selectedQuote} onValueChange={setSelectedQuote}><SelectTrigger aria-label="Devis FIT accepté"><SelectValue placeholder="Choisir un devis accepté" /></SelectTrigger><SelectContent>{quotes.map(q=><SelectItem key={q.id} value={q.id}>{q.quote_family_reference||q.quote_number} · V{q.version_number} · {q.client_name}</SelectItem>)}</SelectContent></Select><Button onClick={generate} disabled={!selectedQuote||busy==="generate"}>{busy==="generate"?<Loader2 className="h-4 w-4 animate-spin"/>:<Plus className="h-4 w-4"/>} Générer les demandes</Button></Card>
    <div className="grid gap-3 grid-cols-2 lg:grid-cols-6"><Metric icon={Clock3} label="Réponses attendues" value={stats.waiting}/><Metric icon={AlertTriangle} label="Holds expirants" value={stats.holds}/><Metric icon={AlertTriangle} label="Indisponibles" value={stats.unavailable}/><Metric icon={RefreshCw} label="Alternatives" value={stats.alternatives}/><Metric icon={CheckCircle2} label="Confirmés" value={stats.confirmed}/><Metric icon={WalletCards} label="Paiements proches" value={stats.payments}/></div>
    {loading?<Card className="p-10 text-center text-muted-foreground"><Loader2 className="mx-auto h-5 w-5 animate-spin"/> Chargement…</Card>:rows.length===0?<Card className="p-10 text-center text-muted-foreground"><PackageCheck className="mx-auto mb-2 h-6 w-6"/>Aucune demande fournisseur. Sélectionnez un devis accepté.</Card>:<div className="space-y-3">{rows.map(row=>{const d=drafts[row.id]||row;const rowAlts=alternatives.filter(a=>a.request_id===row.id&&a.decision==="pending");const overdue=d.follow_up_at&&new Date(d.follow_up_at)<new Date()&&!terminalStatuses.includes(d.status);return <details key={row.id} className={`group rounded-md border bg-background ${overdue||d.status==="unavailable"?"border-amber-300":"border-border"}`}>
      <summary className="flex min-h-16 cursor-pointer list-none items-center justify-between gap-3 p-4"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="truncate font-semibold">{row.service_label}</p><Badge variant={d.status==="confirmed"?"default":d.status==="unavailable"?"destructive":"outline"}>{statusLabels[d.status]}</Badge>{overdue&&<Badge variant="destructive">Relance en retard</Badge>}</div><p className="mt-1 text-xs text-muted-foreground">{row.quote?.quote_family_reference||row.quote?.quote_number} · V{row.version_number} · {row.service_type} · {row.supplier?.name||"Fournisseur non assigné"}</p></div><span className="text-sm font-medium">{d.confirmed_cost!=null?`${Number(d.confirmed_cost).toLocaleString("fr-FR")} ${d.currency}`:"À chiffrer"}</span></summary>
      <div className="grid gap-4 border-t p-4 lg:grid-cols-3"><div className="space-y-3"><Field label="Fournisseur"><Select value={d.supplier_id||"none"} onValueChange={v=>updateDraft(row.id,"supplier_id",v==="none"?"":v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Non assigné</SelectItem>{suppliers.map(s=><SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>)}</SelectContent></Select></Field><Field label="Responsable"><Select value={d.assigned_staff_id||"none"} onValueChange={v=>updateDraft(row.id,"assigned_staff_id",v==="none"?"":v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Non assigné</SelectItem>{staff.map(person=><SelectItem key={person.id} value={person.id}>{person.full_name||"Équipe interne"}</SelectItem>)}</SelectContent></Select></Field><Field label="Statut"><Select value={d.status} onValueChange={v=>updateDraft(row.id,"status",v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{statusOptions.map(s=><SelectItem key={s} value={s}>{statusLabels[s]}</SelectItem>)}</SelectContent></Select></Field><Field label="Relance (heures)"><Input inputMode="numeric" value={d.follow_up_hours} onChange={e=>updateDraft(row.id,"follow_up_hours",e.target.value)}/></Field></div>
      <div className="space-y-3"><DateField label="Relance prévue" value={d.follow_up_at} onChange={v=>updateDraft(row.id,"follow_up_at",v)}/><DateField label="Fin option / hold" value={d.hold_release_deadline} onChange={v=>updateDraft(row.id,"hold_release_deadline",v)}/><DateField label="Annulation sans frais" value={d.cancellation_deadline} onChange={v=>updateDraft(row.id,"cancellation_deadline",v)}/><DateField label="Échéance paiement" value={d.payment_deadline} onChange={v=>updateDraft(row.id,"payment_deadline",v)}/></div>
      <div className="space-y-3"><Field label="N° confirmation"><Input value={d.confirmation_number||""} onChange={e=>updateDraft(row.id,"confirmation_number",e.target.value)}/></Field><div className="grid grid-cols-2 gap-2"><Field label="Coût devisé"><Input inputMode="decimal" value={d.supplier_quoted_cost??""} onChange={e=>updateDraft(row.id,"supplier_quoted_cost",e.target.value)}/></Field><Field label="Coût confirmé"><Input inputMode="decimal" value={d.confirmed_cost??""} onChange={e=>updateDraft(row.id,"confirmed_cost",e.target.value)}/></Field></div><Field label="Réponse fournisseur"><Textarea rows={2} value={d.supplier_response||""} onChange={e=>updateDraft(row.id,"supplier_response",e.target.value)}/></Field><Field label="Notes fournisseur"><Textarea rows={2} value={d.supplier_notes||""} onChange={e=>updateDraft(row.id,"supplier_notes",e.target.value)}/></Field><Button className="w-full" onClick={()=>save(row)} disabled={busy===row.id}>{busy===row.id?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>} Enregistrer</Button></div></div>
      {rowAlts.map(alt=><div key={alt.id} className="m-4 rounded-md border border-amber-200 bg-amber-50 p-4 text-sm"><p className="font-semibold">Alternative : {alt.title}</p><p className="mt-1 text-muted-foreground">{alt.description||"Sans description"}</p><div className="mt-2 flex flex-wrap gap-3"><span>Écart : <strong>{fmtMAD(alt.price_difference_mad)}</strong></span><span>Impact marge : <strong>{fmtMAD(alt.margin_impact_mad)}</strong></span><span>Impact opérationnel : <strong>{alt.operational_impact||"—"}</strong></span></div><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" onClick={()=>decide(alt,"accepted")}>Accepter en interne</Button><Button size="sm" variant="outline" onClick={()=>decide(alt,"rejected")}>Refuser</Button><Button size="sm" variant="secondary" onClick={()=>decide(alt,"client_revision")}><FileText className="h-4 w-4"/>Créer une révision client</Button></div></div>)}
      {attachments.some(file=>file.request_id===row.id)&&<div className="m-4 flex flex-wrap gap-2">{attachments.filter(file=>file.request_id===row.id).map(file=><Button key={file.id} size="sm" variant="outline" onClick={()=>openFile(file)}><FileText className="h-4 w-4"/>{file.file_name}</Button>)}</div>}
    </details>})}</div>}
  </div>;
}
function Metric({icon:Icon,label,value}:{icon:any;label:string;value:number}){return <Card className="rounded-md p-3"><Icon className="h-4 w-4 text-accent"/><p className="mt-2 text-2xl font-semibold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></Card>}
function Field({label,children}:{label:string;children:any}){return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>}
function DateField({label,value,onChange}:{label:string;value:any;onChange:(v:string)=>void}){const local=value?String(value).slice(0,16):"";return <Field label={label}><Input type="datetime-local" value={local} onChange={e=>onChange(e.target.value?new Date(e.target.value).toISOString():"")}/></Field>}
