-- Secure anonymous FIT quote access.
-- Anonymous users never receive direct access to FIT base tables: every read and
-- action resolves the private token server-side and returns an explicit safe shape.

alter table public.fit_quotes
  add column if not exists public_link_expires_at timestamptz,
  add column if not exists public_link_revoked_at timestamptz,
  add column if not exists public_client_visible boolean not null default false,
  add column if not exists public_last_viewed_at timestamptz,
  add column if not exists public_client_status text,
  add column if not exists public_deposit_mad numeric;

-- Existing enabled links remain usable, while becoming explicitly client-visible.
update public.fit_quotes
set public_client_visible = true
where share_enabled = true
  and share_token is not null
  and public_client_visible = false;

create unique index if not exists fit_quotes_share_token_uidx
  on public.fit_quotes (share_token)
  where share_token is not null;

create index if not exists fit_quotes_public_link_active_idx
  on public.fit_quotes (share_enabled, public_link_expires_at)
  where deleted_at is null and share_token is not null;

create table if not exists public.fit_quote_public_audit_events (
  id bigint generated by default as identity primary key,
  quote_id uuid not null references public.fit_quotes(id) on delete cascade,
  event text not null check (event in ('opened', 'accepted', 'revision_requested', 'declined')),
  occurred_at timestamptz not null default now(),
  actor_type text not null default 'anonymous_client' check (actor_type = 'anonymous_client'),
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists fit_quote_public_audit_quote_time_idx
  on public.fit_quote_public_audit_events (quote_id, occurred_at desc);

alter table public.fit_quote_public_audit_events enable row level security;

revoke all on public.fit_quote_public_audit_events from anon, authenticated;

-- Remove every historical anonymous path to FIT records. Authenticated staff access
-- remains controlled by the existing RLS policies.
drop policy if exists "public read shared fit quotes" on public.fit_quotes;
drop policy if exists "public update shared fit quote response" on public.fit_quotes;
drop policy if exists "public read shared fit quote days" on public.fit_quote_days;
drop policy if exists "public read visible shared fit quote day lines" on public.fit_quote_day_cost_lines;
drop policy if exists "public read shared fit quote hotels" on public.fit_quote_hotel_lines;
drop policy if exists "public read shared fit quote flights" on public.fit_quote_flight_lines;

revoke all on public.fit_quotes from anon;
revoke all on public.fit_quote_days from anon;
revoke all on public.fit_quote_day_cost_lines from anon;
revoke all on public.fit_quote_cost_lines from anon;
revoke all on public.fit_quote_hotel_lines from anon;
revoke all on public.fit_quote_flight_lines from anon;
revoke all on public.fit_quote_documents from anon;
revoke all on public.agency_fit_requests from anon;

create or replace function public._resolve_public_fit_quote_token(p_token text)
returns uuid
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select q.id
  from public.fit_quotes q
  where p_token is not null
    and length(p_token) between 24 and 128
    and p_token ~ '^[A-Za-z0-9_-]+$'
    and q.share_token = p_token
    and q.share_enabled = true
    and q.public_link_revoked_at is null
    and (q.public_link_expires_at is null or q.public_link_expires_at > statement_timestamp())
    and q.deleted_at is null
    and q.public_client_visible = true
    and (
      q.status in (
        'sent', 'sent_to_client', 'quoted', 'accepted', 'client_preapproved',
        'modification_requested', 'client_modification_requested', 'revision_requested',
        'pending_lejapon_review', 'pending_japan_availability', 'japan_request_sent',
        'japan_quote_received', 'admin_approved_for_payment', 'payment_authorized',
        'partner_payment_pending', 'partner_payment_received', 'booking_in_progress',
        'partially_confirmed', 'confirmed', 'converted_to_booking'
      )
      or q.status = 'draft'
    )
  limit 1
$$;

revoke all on function public._resolve_public_fit_quote_token(text) from public, anon, authenticated;

create or replace function public.get_public_fit_quote_by_token(p_token text)
returns jsonb
language plpgsql
volatile
security definer
set search_path = pg_catalog, public
as $$
declare
  v_quote_id uuid;
  v_result jsonb;
begin
  v_quote_id := public._resolve_public_fit_quote_token(p_token);
  if v_quote_id is null then
    return null;
  end if;

  select jsonb_build_object(
    'fit_reference', q.quote_number,
    'client_display_name', coalesce(nullif(trim(q.client_name), ''), 'Cher client'),
    'destination', coalesce(
      nullif((select string_agg(distinct d.city, ' → ' order by d.city)
              from public.fit_quote_days d
              where d.quote_id = q.id and nullif(trim(d.city), '') is not null), ''),
      'Japon'
    ),
    'dates', jsonb_build_object('start', q.travel_start_date, 'end', q.travel_end_date),
    'travelers', q.travelers_count,
    'hotel_level', q.hotel_category,
    'room_type', q.room_type,
    'programme', jsonb_build_object(
      'days', coalesce((
        select jsonb_agg(jsonb_build_object(
          'key', d.day_number,
          'day_number', d.day_number,
          'date', d.date,
          'title', d.title,
          'city', d.city,
          'description', coalesce(d.optimized_client_description, d.description_client),
          'summary', coalesce(d.sales_summary, d.client_summary),
          'highlights', coalesce(d.client_highlights, '[]'::jsonb),
          'included_services', coalesce(d.client_inclusions, d.visits, '[]'::jsonb),
          'visible_extras', coalesce(d.client_options, d.optional_visits, '[]'::jsonb),
          'pace', coalesce(d.day_pace, d.rhythm),
          'transport', coalesce(d.transport_modes, '[]'::jsonb),
          'meals', coalesce(d.meal_plan, d.meals, '[]'::jsonb),
          'public_meal_notes', d.meal_notes,
          'selling_price', d.selling_price_mad,
          'images', coalesce(d.image_urls, '[]'::jsonb)
        ) order by d.sort_order, d.day_number)
        from public.fit_quote_days d where d.quote_id = q.id
      ), '[]'::jsonb),
      'hotels', coalesce((
        select jsonb_agg(jsonb_build_object(
          'city', h.city, 'name', h.hotel_name, 'image', h.image_url,
          'level', h.category, 'room_type', h.room_type, 'nights', h.nights,
          'public_notes', h.public_notes
        ) order by h.sort_order)
        from public.fit_quote_hotel_lines h where h.quote_id = q.id
      ), '[]'::jsonb),
      'flights', coalesce((
        select jsonb_agg(jsonb_build_object(
          'route', f.route, 'airline', f.airline, 'status', f.status,
          'travelers', f.passengers_count, 'public_notes', f.public_notes
        ) order by f.sort_order)
        from public.fit_quote_flight_lines f where f.quote_id = q.id
      ), '[]'::jsonb)
    ),
    'included_services', coalesce(q.inclusions, ''),
    'excluded_services', coalesce(q.exclusions, q.non_included_text, ''),
    'visible_extras', coalesce((
      select jsonb_agg(jsonb_build_object(
        'day_key', (select d.day_number from public.fit_quote_days d where d.id = l.day_id),
        'category', l.category,
        'label', l.label,
        'optional', l.is_optional
      ) order by l.sort_order)
      from public.fit_quote_day_cost_lines l
      where l.quote_id = q.id and l.is_client_visible = true
    ), '[]'::jsonb),
    'public_notes', jsonb_build_object(
      'general', q.production_public_note,
      'payment', q.payment_conditions,
      'cancellation', q.cancellation_conditions
    ),
    'selling_price', jsonb_build_object(
      'total', q.total_selling_price_mad,
      'per_traveler', q.price_per_person_mad,
      'currency', q.currency
    ),
    'deposit', q.public_deposit_mad,
    'validity_date', q.valid_until,
    'status', coalesce(q.public_client_status,
      case
        when q.status in ('accepted', 'client_preapproved') then 'accepted'
        when q.status in ('modification_requested', 'client_modification_requested', 'revision_requested') then 'revision_requested'
        when q.status = 'rejected' then 'declined'
        else 'quoted'
      end),
    'client_pdf_link', (
      select doc.public_url
      from public.fit_quote_documents doc
      where doc.quote_id = q.id
        and doc.document_type = 'client_pdf'
        and nullif(trim(doc.public_url), '') is not null
      order by doc.created_at desc
      limit 1
    )
  ) into v_result
  from public.fit_quotes q
  where q.id = v_quote_id;

  update public.fit_quotes
  set public_last_viewed_at = statement_timestamp()
  where id = v_quote_id;

  insert into public.fit_quote_public_audit_events (quote_id, event)
  values (v_quote_id, 'opened');

  return v_result;
end;
$$;

create or replace function public.accept_public_fit_quote(p_token text, p_client_notes text default null)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_quote_id uuid;
  v_event_at timestamptz := statement_timestamp();
begin
  v_quote_id := public._resolve_public_fit_quote_token(p_token);
  if v_quote_id is null then return null; end if;
  if length(coalesce(p_client_notes, '')) > 2000 then raise exception 'client notes too long'; end if;

  update public.fit_quotes q
  set status = case when q.quote_channel = 'partner' then 'client_preapproved' else 'accepted' end,
      production_status = case when q.quote_channel = 'partner' then 'pending_lejapon_review' else q.production_status end,
      public_client_status = 'accepted',
      client_notes = nullif(trim(p_client_notes), ''),
      accepted_at = v_event_at,
      client_preapproved_at = v_event_at,
      client_preapproved_by = 'anonymous_client'
  where q.id = v_quote_id;

  insert into public.fit_quote_public_audit_events (quote_id, event, occurred_at, metadata)
  values (v_quote_id, 'accepted', v_event_at, jsonb_build_object('has_notes', nullif(trim(p_client_notes), '') is not null));
  return jsonb_build_object('status', 'accepted', 'event_at', v_event_at);
end;
$$;

create or replace function public.request_public_fit_quote_revision(p_token text, p_client_notes text default null)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_quote_id uuid;
  v_event_at timestamptz := statement_timestamp();
begin
  v_quote_id := public._resolve_public_fit_quote_token(p_token);
  if v_quote_id is null then return null; end if;
  if length(coalesce(p_client_notes, '')) > 2000 then raise exception 'client notes too long'; end if;

  update public.fit_quotes
  set status = 'client_modification_requested',
      production_status = 'client_modification_requested',
      public_client_status = 'revision_requested',
      client_notes = nullif(trim(p_client_notes), ''),
      requested_changes_at = v_event_at
  where id = v_quote_id;

  insert into public.fit_quote_public_audit_events (quote_id, event, occurred_at, metadata)
  values (v_quote_id, 'revision_requested', v_event_at, jsonb_build_object('has_notes', nullif(trim(p_client_notes), '') is not null));
  return jsonb_build_object('status', 'revision_requested', 'event_at', v_event_at);
end;
$$;

create or replace function public.decline_public_fit_quote(p_token text, p_client_notes text default null)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_quote_id uuid;
  v_event_at timestamptz := statement_timestamp();
begin
  v_quote_id := public._resolve_public_fit_quote_token(p_token);
  if v_quote_id is null then return null; end if;
  if length(coalesce(p_client_notes, '')) > 2000 then raise exception 'client notes too long'; end if;

  update public.fit_quotes
  set status = 'rejected',
      production_status = 'rejected',
      public_client_status = 'declined',
      client_notes = nullif(trim(p_client_notes), '')
  where id = v_quote_id;

  insert into public.fit_quote_public_audit_events (quote_id, event, occurred_at, metadata)
  values (v_quote_id, 'declined', v_event_at, jsonb_build_object('has_notes', nullif(trim(p_client_notes), '') is not null));
  return jsonb_build_object('status', 'declined', 'event_at', v_event_at);
end;
$$;

-- Authenticated link management centralizes cryptographically secure token creation.
create or replace function public.regenerate_public_fit_quote_token(p_quote_id uuid, p_expires_at timestamptz default null)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_token text;
begin
  if auth.uid() is null or not public.can_access_fit_quote(p_quote_id, auth.uid()) then
    raise exception 'not authorized';
  end if;
  v_token := encode(extensions.gen_random_bytes(32), 'hex');
  update public.fit_quotes
  set share_token = v_token,
      share_enabled = true,
      public_client_visible = true,
      public_link_expires_at = p_expires_at,
      public_link_revoked_at = null,
      public_client_status = coalesce(public_client_status, 'quoted')
  where id = p_quote_id;
  return jsonb_build_object('token', v_token, 'expires_at', p_expires_at, 'enabled', true);
end;
$$;

create or replace function public.set_public_fit_quote_link(
  p_quote_id uuid,
  p_enabled boolean,
  p_expires_at timestamptz default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_token text;
begin
  if auth.uid() is null or not public.can_access_fit_quote(p_quote_id, auth.uid()) then
    raise exception 'not authorized';
  end if;
  select share_token into v_token from public.fit_quotes where id = p_quote_id;
  if p_enabled and v_token is null then raise exception 'generate a token first'; end if;
  update public.fit_quotes
  set share_enabled = p_enabled,
      public_client_visible = case when p_enabled then true else public_client_visible end,
      public_link_expires_at = p_expires_at,
      public_link_revoked_at = case when p_enabled then null else statement_timestamp() end
  where id = p_quote_id;
  return jsonb_build_object('enabled', p_enabled, 'expires_at', p_expires_at);
end;
$$;

revoke all on function public.get_public_fit_quote_by_token(text) from public;
revoke all on function public.accept_public_fit_quote(text, text) from public;
revoke all on function public.request_public_fit_quote_revision(text, text) from public;
revoke all on function public.decline_public_fit_quote(text, text) from public;
grant execute on function public.get_public_fit_quote_by_token(text) to anon, authenticated;
grant execute on function public.accept_public_fit_quote(text, text) to anon, authenticated;
grant execute on function public.request_public_fit_quote_revision(text, text) to anon, authenticated;
grant execute on function public.decline_public_fit_quote(text, text) to anon, authenticated;

revoke all on function public.regenerate_public_fit_quote_token(uuid, timestamptz) from public;
revoke all on function public.set_public_fit_quote_link(uuid, boolean, timestamptz) from public;
grant execute on function public.regenerate_public_fit_quote_token(uuid, timestamptz) to authenticated;
grant execute on function public.set_public_fit_quote_link(uuid, boolean, timestamptz) to authenticated;

notify pgrst, 'reload schema';
